### PR TITLE
Customization, ESLint, Updates

### PR DESCRIPTION
**Pull request by brettz9**
Builds on #56 

- Breaking enhancement: Avoid `process.env` (`app.js` accepts CLI now instead)
- Breaking enhancement: Allow app to pass in own countries list
- Breaking refactoring: `EmailDispatcher` and `AccountManager` are now classes; routes accepts config
- Update: Use now required Mongodb APIs
- Linting (ESLint): Apply eslint-config-ash-nazg
- Refactoring: Destructuring; arrow functions for handlers; utilize succincter stylus features; Promises
- npm: Update deps and devDeps; put deps, devDeps together
- npm: Remove redundant `private: false`

I'd appreciate knowing if you're still maintaining, so that if not, I might just publish my own fork. Thanks!

### CODE REVIEW

**Comment by brettz9** [comment]
Hi. @braitsch , are you planning to still review PRs?

**Comment by nicotravassos** [comment]
Hi @brettz9,

I love this PR but it seems this project has reached its end of time it would be really cool if you could continue within your own fork.

**Comment by brettz9** [comment]
Sure, and thanks, @nicotravassos .  I am trying to wrap up some work on an i18n subproject intended for use within my fork of node-login, and then have some more to-dos within node-login proper, but I can look into making an independent project after that if this project is no longer being maintained.

**Comment by nicotravassos** [comment]
Thats great thank you @brettz9

**Comment by brettz9** [comment]
Closing as hadn't heard back and incorporated in https://github.com/brettz9/nogin/

**Pull request closed without merging**
